apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
spec:
  replicas: 2   
  selector:
    matchLabels:
      app: be 
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: img1
          image: nginx
          resources:
            requests:
                cpu: 250m
            limits:
                cpu: 500m
