apiVersion: v1
kind: RoleBinding
metadata:
  name: my-rb
  namespace: developer 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role 
  name: myrole 
subjects:
  - apiGroup: User
    name: User
    apiGroup: rbac.authorization.k8s.io
